apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: pdf-to-mp3
data:
  RECAPTCHA_SITE_KEY: "6LckdpwsAAAAAAgdQ_-BKQUuOWkO5cO4R98WP8sB"
  WORKER_IMAGE: "ghcr.io/kenty911/pdf_read_worker:latest"  # CI により自動更新
