apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pdf-to-mp3
  namespace: pdf-to-mp3
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  ingressClassName: nginx
  rules:
    - host: pdf-to-mp3.example.com   # 要変更
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flask
                port:
                  number: 80
