apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-data
  namespace: pdf-to-mp3
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
