apiVersion: v1
kind: ConfigMap
metadata:
  name: worker-config
  namespace: pdf-to-mp3
data:
  VOICEVOX_ONNXRUNTIME_PATH: "/app/voicevox/onnxruntime/lib/libvoicevox_onnxruntime.so.1.17.3"
  VOICEVOX_DICT_DIR: "/app/voicevox/dict/open_jtalk_dic_utf_8-1.11"
  VOICEVOX_VVM_PATH: "/app/voicevox/models/vvms/0.vvm"
